version: '3.8'

services:
  postgres:
    container_name: motoboy_postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: motoboy_delivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - motoboy_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: motoboy_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - motoboy_network
    restart: unless-stopped
    depends_on:
      - postgres

networks:
  motoboy_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: 