spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/combobackend
    username: combo_user
    password: combo_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
