spring:
  application:
    name: motoboy-delivery-service

  datasource:
    url: jdbc:postgresql://localhost:5432/motoboy_delivery
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.sbaldasso.combobackend: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

security:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret}
    expiration: 86400000 # 24 hours

app:
  cors:
    allowed-origins: http://localhost:3000
  location:
    update-interval-seconds: 10
  notification:
    cleanup-older-than-days: 30
